def add(n1, n2):
    return n1 + n2


# number1 = 10
# number2 = input("Please provide a number:")
# add(number1, number2)

# The program crashes because the entered number is one string

# USING TRY/EXCEPTION
try:
    result = add(10, 'a')
except:
    print("Hey it looks like your aren't adding correctly")
else:
    # Code that runs if there is no exception
    print("Add went well")
    print(result)

# Another example using FINALLY

try:
    f = open('testfile', 'r')
    f.write("Write a test line")
except TypeError:
    print("There was a type error")
except OSError:
    print("Hey you have an OS Error")
except:
    print("All other exceptions")
# Finally block is always executed
finally:
    print("I always run")


# Using try/exception into one function

def ask_for_int():
    try:
        result = int(input("Please provide a number: "))
    except:
        print("Whoops! That is not a number")
    finally:
        print("End of try/except/finally")


ask_for_int()
